// tslint:disable
/**
 * JWTToken_Auth_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    EventjoinusersVM,
} from './';

/**
 * @export
 * @interface AddEventJoinUserVM
 */
export interface AddEventJoinUserVM {
    /**
     * @type {string}
     * @memberof AddEventJoinUserVM
     */
    eventId?: string;
    /**
     * @type {Array<EventjoinusersVM>}
     * @memberof AddEventJoinUserVM
     */
    joinUsers?: Array<EventjoinusersVM> | null;
}
