// tslint:disable
/**
 * JWTToken_Auth_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    EventjoinusersVM,
} from './';

/**
 * @export
 * @interface EventVM
 */
export interface EventVM {
    /**
     * @type {string}
     * @memberof EventVM
     */
    id?: string;
    /**
     * @type {string}
     * @memberof EventVM
     */
    name?: string | null;
    /**
     * @type {string}
     * @memberof EventVM
     */
    startTime?: string | null;
    /**
     * @type {string}
     * @memberof EventVM
     */
    endTime?: string | null;
    /**
     * @type {string}
     * @memberof EventVM
     */
    address?: string | null;
    /**
     * @type {number}
     * @memberof EventVM
     */
    cost?: number;
    /**
     * @type {Array<EventjoinusersVM>}
     * @memberof EventVM
     */
    eventjoinusersName?: Array<EventjoinusersVM> | null;
}
