// tslint:disable
/**
 * JWTToken_Auth_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface EventjoinusersVM
 */
export interface EventjoinusersVM {
    /**
     * @type {number}
     * @memberof EventjoinusersVM
     */
    userId?: number;
    /**
     * @type {string}
     * @memberof EventjoinusersVM
     */
    userName?: string | null;
}
