// tslint:disable
/**
 * JWTToken_Auth_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface GetUserVM
 */
export interface GetUserVM {
    /**
     * @type {string}
     * @memberof GetUserVM
     */
    email?: string | null;
    /**
     * @type {string}
     * @memberof GetUserVM
     */
    createTime?: string;
    /**
     * @type {string}
     * @memberof GetUserVM
     */
    img?: string | null;
    /**
     * @type {string}
     * @memberof GetUserVM
     */
    chiName?: string | null;
    /**
     * @type {string}
     * @memberof GetUserVM
     */
    engName?: string | null;
    /**
     * @type {string}
     * @memberof GetUserVM
     */
    phone?: string | null;
    /**
     * @type {string}
     * @memberof GetUserVM
     */
    gender?: string | null;
    /**
     * @type {string}
     * @memberof GetUserVM
     */
    birthDay?: string;
    /**
     * @type {string}
     * @memberof GetUserVM
     */
    address?: string | null;
    /**
     * @type {boolean}
     * @memberof GetUserVM
     */
    isSubscribe?: boolean;
}
