// tslint:disable
/**
 * JWTToken_Auth_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface LoginVM
 */
export interface LoginVM {
    /**
     * @type {string}
     * @memberof LoginVM
     */
    email?: string | null;
    /**
     * @type {string}
     * @memberof LoginVM
     */
    pwd?: string | null;
    /**
     * @type {boolean}
     * @memberof LoginVM
     */
    rememberMe?: boolean;
    /**
     * @type {string}
     * @memberof LoginVM
     */
    recaptchaToken?: string | null;
}
