// tslint:disable
/**
 * JWTToken_Auth_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface MemberVM
 */
export interface MemberVM {
    /**
     * @type {number}
     * @memberof MemberVM
     */
    id?: number;
    /**
     * @type {string}
     * @memberof MemberVM
     */
    chiName?: string | null;
    /**
     * @type {string}
     * @memberof MemberVM
     */
    gender?: string | null;
    /**
     * @type {string}
     * @memberof MemberVM
     */
    birth?: string | null;
    /**
     * @type {string}
     * @memberof MemberVM
     */
    idNumber?: string | null;
    /**
     * @type {string}
     * @memberof MemberVM
     */
    email?: string | null;
    /**
     * @type {string}
     * @memberof MemberVM
     */
    phone?: string | null;
    /**
     * @type {string}
     * @memberof MemberVM
     */
    address?: string | null;
    /**
     * @type {string}
     * @memberof MemberVM
     */
    school?: string | null;
    /**
     * @type {string}
     * @memberof MemberVM
     */
    department?: string | null;
}
